server:
  port: 8080
    
spring:
  mvc:
    async:
      request-timeout: 30000
    static-path-pattern: /static/**
    view:
      suffix: .html
  datasource:
    url: jdbc:log4jdbc:mariadb://mutec.iptime.org:3306/healthvision?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&autoReconnect=true'
    username: healthvision
    password: healthvision123!@#
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      leak-detection-threshold: 60000
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

mybatis:
  type-aliases-package: com.mutecsoft.healthvision.common.model, com.mutecsoft.healthvision.common.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/*.xml

springdoc:
  packages-to-scan: com.mutecsoft.healthvision.api.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
      
jwt:
  access-expire-time: 5  #인증만료일자 (시간)
  refresh-expire-day: 20  #인증만료일자 (일)
  password-expire-minute: 10 #인증만료일자 (분)
  base64:
    secret: health-vision-2025 #인증암화키

file:
  base-path: /home/mutecsoft/healthvision/upload 